= Quick Setup Guide For MAMDAU Version 2

=== Installation of code on Raspberry Pi:

1. Install Raspian OS on a micro-sd card
2. Put Micro-SD card into a flash drive and open it on a Raspbery Pi that you can easily access the OS on.
3. Create the following directories in `/home/pi/`: `/Mamdau2DATA` and `/Mamdau2CODE`
4. Once those are made copy the `V2` source code and place into `/home/pi/Mamdau2CODE`
5. After those have been succesfully placed open the Terminal
6. In the Terminal type the following: `sudo crontab -e` and choose the editor of your choice
7. Once you have typed the command you should have gotten something that says at the top: `Edit this file to introduce tasks to be run by cron.` In here type the following: `@reboot sudo bash /home/pi/Mamdau2CODE/services_start.sh`
8. Save
9. Now unplug the Micro-SD card that you have been working on from the Raspberry Pi and now plug it into the Pi that you will be using for the launch.
10. Plug in the power and the Pi will automatically start collecting data. 

=== How to start recording data:

1. Place batteries inside Geiger Counter
2. Make sure all components are properly connected
3. Make sure the micro-sd card is inserted into the raspberry pi zero
4. Turn on Geiger Counter first
5. Switch on the battery pack and wait about a minute for the system to start recording data 

=== How to retrieve data

1. Switch off the power from the battery back
2. Switch off the power on the Geiger Counter
3. Remove the micro-sd card from the raspberry pi zero
4. Open the micro-sd card on a linux device (the filesystem cannot be opened on a Windows device)
5. The location of data should be under `/home/pi/Mamdau2DATA/`